# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEST4hI-onwGBclbGjq7gq0qPJF5lMKE
"""

def decbin(n):
    """Convierte decimal a binario (sin usar bin())."""
    if n == 0:
        return "0"
    resultado = ""
    while n > 0:
        resultado = str(n % 2) + resultado
        n //= 2
    return resultado

def dechex(n):
    """Convierte decimal a hexadecimal (sin usar hex())."""
    if n == 0:
        return "0"
    hex_chars = "0123456789ABCDEF"
    resultado = ""
    while n > 0:
        resultado = hex_chars[n % 16] + resultado
        n //= 16
    return resultado

def decoc(n):
    """Convierte decimal a octal (sin usar oct())."""
    if n == 0:
        return "0"
    resultado = ""
    while n > 0:
        resultado = str(n % 8) + resultado
        n //= 8
    return resultado

def bindec(b):
    """Convierte binario (string) a decimal."""
    resultado = 0
    potencia = 0
    for digito in reversed(b):
        if digito not in ("0", "1"):
            raise ValueError("Número binario inválido")
        resultado += int(digito) * (2 ** potencia)
        potencia += 1
    return resultado

def hexdec(h):
    """Convierte hexadecimal (string) a decimal."""
    hex_chars = "0123456789ABCDEF"
    h = h.strip().upper()
    resultado = 0
    potencia = 0
    for digito in reversed(h):
        if digito not in hex_chars:
            raise ValueError("Hexadecimal inválido")
        valor = hex_chars.index(digito)
        resultado += valor * (16 ** potencia)
        potencia += 1
    return resultado

def ocdec(o):
    """Convierte octal (string) a decimal."""
    resultado = 0
    potencia = 0
    for digito in reversed(o):
        if digito not in "01234567":
            raise ValueError("Octal inválido")
        resultado += int(digito) * (8 ** potencia)
        potencia += 1
    return resultado


# HISTORIAL (cola circular de tamaño 5)
HIST_SIZE = 5
historial = [None] * HIST_SIZE
pos_hist = 0
count_hist = 0

def guardar_historial(entrada):
    global pos_hist, count_hist
    historial[pos_hist] = entrada
    pos_hist = (pos_hist + 1) % HIST_SIZE
    if count_hist < HIST_SIZE:
        count_hist += 1

def mostrar_historial():
    """Muestra el historial desde el más antiguo al más reciente."""
    if count_hist == 0:
        print("Historial vacío.")
        return

    print("\n--- ÚLTIMAS 5 OPERACIONES ---")

    if count_hist < HIST_SIZE:
        for i in range(count_hist):
            print(f"{i+1}. {historial[i]}")
    else:
        idx = pos_hist
        for i in range(HIST_SIZE):
            print(f"{i+1}. {historial[idx]}")
            idx = (idx + 1) % HIST_SIZE

# FUNCION PARA VOLVER A EMPEZAR
def volver_a_empezar():
    """Pregunta si el usuario desea continuar o salir."""
    while True:
        opcion = input("\n¿Deseas volver al menú principal? (s/n): ").lower()
        if opcion == "s":
            return True
        elif opcion == "n":
            print("Gracias por usar el programa. ¡Hasta luego!")
            return False
        else:
            print("Opción inválida, escribe 's' o 'n'.")


# MENÚ PRINCIPAL
def menu():
    while True:
        print("\n=== CALCULADORA DE CONVERSIONES ===")
        print("1. Decimal a Binario")
        print("2. Decimal a Hexadecimal")
        print("3. Decimal a Octal")
        print("4. Binario a Decimal")
        print("5. Hexadecimal a Decimal")
        print("6. Octal a Decimal")
        print("7. Mostrar Historial (últimas 5)")
        print("8. Salir")

        op = input("Elige una opción: ").strip()

        try:
            if op in ["1", "2", "3"]:
                valor = int(input("Ingresa un número decimal: ").strip())

                if valor < 0:
                    print("El número debe ser entero positivo.")
                    continue

                if op == "1":
                    convertido = decbin(valor)
                    salida = f"{valor} Dec -> {convertido} Bin"
                    print("Binario:", convertido)

                elif op == "2":
                    convertido = dechex(valor)
                    salida = f"{valor} Dec -> {convertido} Hex"
                    print("Hexadecimal:", convertido)

                elif op == "3":
                    convertido = decoc(valor)
                    salida = f"{valor} Dec -> {convertido} Oct"
                    print("Octal:", convertido)

                guardar_historial(salida)

            elif op == "4":
                binario = input("Ingresa un número binario: ").strip()
                convertido = bindec(binario)
                salida = f"{binario} Bin -> {convertido} Dec"
                print("Decimal:", convertido)
                guardar_historial(salida)

            elif op == "5":
                hex_num = input("Ingresa un número hexadecimal: ").strip()
                convertido = hexdec(hex_num)
                salida = f"{hex_num.upper()} Hex -> {convertido} Dec"
                print("Decimal:", convertido)
                guardar_historial(salida)

            elif op == "6":
                octal = input("Ingresa un número octal: ").strip()
                convertido = ocdec(octal)
                salida = f"{octal} Oct -> {convertido} Dec"
                print("Decimal:", convertido)
                guardar_historial(salida)

            elif op == "7":
                mostrar_historial()

            elif op == "8":
                print("bye")
                break

            else:
                print("Opción no válida.")

        except ValueError as ve:
            print("Error:", ve)

        # Preguntar si desea volver
        if not volver_a_empezar():
            break


if __name__ == "__main__":
    menu()